title:  A-J MÃ¤ki, Data Engineer
logo: "https://anahill.github.io/pics/headshot_circle_ajm.png"
description: Data Engineer, PhD
show_downloads: true
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme